project:
  type: website
  output-dir: docs


website:
  title: "Geostatistical Modelling with inlabru"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day1.qmd
        text: Day 1
      - href: day2.qmd
        text: Day 2
      - href: day3.qmd
        text: Day 3
      - text: Slides
        menu:
          - href: slides/day1_slides.qmd
            text: Day 1 slides
          - href: slides/day2_slides.qmd
            text: Day 2 slides
          - href: slides/day3_slides.qmd
            text: Day 3 slides
      - href: data.zip
        text: Download data

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  cache: true
  echo: true
  warning: false
  message: false
